# Site settings
title: 'Cryptic Duo' # Your Title
tagline: 'smart quote' # A brief tagline for your site
sidebar_image: /images/cover.jpg

# Build settings
markdown: redcarpet
highlighter: pygments
baseurl:
